In [1]:
import pandas as pd
import numpy as np

In [2]:
sv = pd.read_csv(r'D:\Datasets\svmfile.csv')

In [3]:
sv.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [5]:
sv.job = le.fit_transform(sv.job)
sv.marital = le.fit_transform(sv.marital)
sv.education = sv.education.replace({'illiterate':0, 'unknown':0, 'basic.4y':1, 'basic.6y':2,
                                    'basic.9y':3, 'high.school':4, 'university.degree':5,
                                    'professional.course':6})
sv.default = sv.default.replace({'no':0, 'unknown':1,'yes':2 })
sv.housing = sv.housing.replace({'no':0, 'unknown':1, 'yes':2 })
sv.loan = sv.loan.replace({'no':0, 'unknown':1, 'yes':2})
sv.contact = le.fit_transform(sv.contact)
sv.month = sv.month.replace({'mar':3, 'apr':4, 'may':5, 'jun':6, 'jul':7,
                            'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12})
sv.day_of_week = sv.day_of_week.replace({'mon':0, 'tue':1, 'wed':2, 'thu':3, 'fri':4})
sv.poutcome = sv.poutcome.replace({'nonexistent':0, 'failure':1, 'success':2})
sv.y = sv.y.replace({'no':0, 'yes':1})

In [6]:
from sklearn.model_selection import train_test_split

sv_train, sv_test = train_test_split(sv, test_size = .2, random_state = 123)

In [7]:
df1 = sv_train[sv_train.y == 1]

In [8]:
sv_train = pd.concat([sv_train, df1])

In [9]:
sv.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          1        0        0     0        1      5   
1   57    7        1          4        1        0     0        1      5   
2   37    7        1          4        0        2     0        1      5   
3   40    0        1          2        0        0     0        1      5   
4   56    7        1          4        0        0     2        1      5   

   day_of_week  ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0            0  ...         1    999         0         0           1.1   
1            0  ...         1    999         0         0           1.1   
2            0  ...         1    999         0         0           1.1   
3            0  ...         1    999         0         0           1.1   
4            0  ...         1    999         0         0           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0  

[5 rows x 21 columns]

In [10]:
sv_train_x = sv_train.iloc[:, 0:-1]
sv_train_y = sv_train.iloc[:, -1]

In [11]:
sv_test_x = sv_test.iloc[:, 0:-1]
sv_test_y = sv_test.iloc[:, -1]

In [12]:
from sklearn.svm import SVC

svm_ds = SVC(kernel = 'poly', degree = 5)

In [13]:
svm_ds.fit(sv_train_x, sv_train_y)

SVC(degree=5, kernel='poly')

In [14]:
pred_svm = svm_ds.predict(sv_test_x)

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
tab_svm = confusion_matrix(sv_test_y, pred_svm)
tab_svm

array([[6948,  350],
       [ 409,  531]], dtype=int64)

In [17]:
222 / (222 + 115)

0.658753709198813

In [18]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [19]:
dt.fit(sv_train_x, sv_train_y)

DecisionTreeClassifier()

In [20]:
pred_dt = dt.predict(sv_test_x)

In [21]:
tab_dt = confusion_matrix(sv_test_y, pred_dt)
tab_dt

array([[6843,  455],
       [ 447,  493]], dtype=int64)

In [22]:
tab_dt.diagonal().sum()/tab_dt.sum()

0.890507404709881

In [23]:
from sklearn.ensemble import AdaBoostClassifier

In [24]:
abc = AdaBoostClassifier(dt)
abc.fit(sv_train_x, sv_train_y)
pred_abc = abc.predict(sv_test_x)

tab_abc = confusion_matrix(sv_test_y, pred_abc)
tab_abc

array([[6825,  473],
       [ 452,  488]], dtype=int64)

In [25]:
tab_abc.diagonal().sum()/tab_abc.sum()

0.8877154649186696